export const timezones = [
    { key: "Pacific/Midway", label: "Midway Island" },
    { key: "Pacific/Samoa", label: "Samoa" },
    { key: "Pacific/Honolulu", label: "Hawaii" },
    { key: "America/Anchorage", label: "Alaska" },
    { key: "America/Los_Angeles", label: "Pacific Time (US & Canada)" },
    { key: "America/Denver", label: "Mountain Time (US & Canada)" },
    { key: "America/Chicago", label: "Central Time (US & Canada)" },
    { key: "America/New_York", label: "Eastern Time (US & Canada)" },
    { key: "America/Caracas", label: "Caracas" },
    { key: "America/Lima", label: "Lima" },
    { key: "America/Santiago", label: "Santiago" },
    { key: "America/Sao_Paulo", label: "São Paulo" },
    { key: "Atlantic/South_Georgia", label: "Mid-Atlantic" },
    { key: "Atlantic/Azores", label: "Azores" },
    { key: "Atlantic/Cape_Verde", label: "Cape Verde Is." },
    { key: "Europe/London", label: "London" },
    { key: "Europe/Paris", label: "Paris" },
    { key: "Europe/Berlin", label: "Berlin" },
    { key: "Europe/Athens", label: "Athens" },
    { key: "Europe/Moscow", label: "Moscow" },
    { key: "Asia/Dubai", label: "Dubai" },
    { key: "Asia/Karachi", label: "Karachi" },
    { key: "Asia/Tashkent", label: "Tashkent" },
    { key: "Asia/Kolkata", label: "India" },
    { key: "Asia/Dhaka", label: "Dhaka" },
    { key: "Asia/Bangkok", label: "Bangkok" },
    { key: "Asia/Jakarta", label: "Jakarta" },
    { key: "Asia/Shanghai", label: "China" },
    { key: "Asia/Hong_Kong", label: "Hong Kong" },
    { key: "Asia/Singapore", label: "Singapore" },
    { key: "Asia/Tokyo", label: "Tokyo" },
    { key: "Asia/Seoul", label: "Seoul" },
    { key: "Australia/Darwin", label: "Darwin" },
    { key: "Australia/Perth", label: "Perth" },
    { key: "Australia/Brisbane", label: "Brisbane" },
    { key: "Australia/Adelaide", label: "Adelaide" },
    { key: "Australia/Sydney", label: "Sydney" },
    { key: "Pacific/Auckland", label: "Auckland" },
    { key: "UTC", label: "UTC" },
];