/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOnboardingRouteImport } from './routes/api/onboarding'
import { Route as ApiCheckEmailIndexRouteImport } from './routes/api/check-email/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedDashboardUsersRouteImport } from './routes/_protected/dashboard/users'
import { Route as ProtectedDashboardUploadRecordingsRouteImport } from './routes/_protected/dashboard/upload-recordings'
import { Route as ProtectedDashboardSettingsRouteImport } from './routes/_protected/dashboard/settings'
import { Route as ProtectedDashboardRiskCenterRouteImport } from './routes/_protected/dashboard/risk-center'
import { Route as ProtectedDashboardKnowledgeBaseRouteImport } from './routes/_protected/dashboard/knowledge-base'
import { Route as ProtectedDashboardCustomRulesRouteImport } from './routes/_protected/dashboard/custom-rules'
import { Route as ProtectedDashboardConversationsRouteImport } from './routes/_protected/dashboard/conversations'
import { Route as ProtectedDashboardBetterAuthRouteImport } from './routes/_protected/dashboard/better-auth'
import { Route as ProtectedDashboardAgentsRouteImport } from './routes/_protected/dashboard/agents'
import { Route as ProtectedDashboardAboutRouteImport } from './routes/_protected/dashboard/about'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingRoute = ApiOnboardingRouteImport.update({
  id: '/api/onboarding',
  path: '/api/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckEmailIndexRoute = ApiCheckEmailIndexRouteImport.update({
  id: '/api/check-email/',
  path: '/api/check-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardUsersRoute = ProtectedDashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardUploadRecordingsRoute =
  ProtectedDashboardUploadRecordingsRouteImport.update({
    id: '/dashboard/upload-recordings',
    path: '/dashboard/upload-recordings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardSettingsRoute =
  ProtectedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardRiskCenterRoute =
  ProtectedDashboardRiskCenterRouteImport.update({
    id: '/dashboard/risk-center',
    path: '/dashboard/risk-center',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardKnowledgeBaseRoute =
  ProtectedDashboardKnowledgeBaseRouteImport.update({
    id: '/dashboard/knowledge-base',
    path: '/dashboard/knowledge-base',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardCustomRulesRoute =
  ProtectedDashboardCustomRulesRouteImport.update({
    id: '/dashboard/custom-rules',
    path: '/dashboard/custom-rules',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardConversationsRoute =
  ProtectedDashboardConversationsRouteImport.update({
    id: '/dashboard/conversations',
    path: '/dashboard/conversations',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardBetterAuthRoute =
  ProtectedDashboardBetterAuthRouteImport.update({
    id: '/dashboard/better-auth',
    path: '/dashboard/better-auth',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardAgentsRoute =
  ProtectedDashboardAgentsRouteImport.update({
    id: '/dashboard/agents',
    path: '/dashboard/agents',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardAboutRoute = ProtectedDashboardAboutRouteImport.update({
  id: '/dashboard/about',
  path: '/dashboard/about',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/dashboard/about': typeof ProtectedDashboardAboutRoute
  '/dashboard/agents': typeof ProtectedDashboardAgentsRoute
  '/dashboard/better-auth': typeof ProtectedDashboardBetterAuthRoute
  '/dashboard/conversations': typeof ProtectedDashboardConversationsRoute
  '/dashboard/custom-rules': typeof ProtectedDashboardCustomRulesRoute
  '/dashboard/knowledge-base': typeof ProtectedDashboardKnowledgeBaseRoute
  '/dashboard/risk-center': typeof ProtectedDashboardRiskCenterRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/upload-recordings': typeof ProtectedDashboardUploadRecordingsRoute
  '/dashboard/users': typeof ProtectedDashboardUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/api/check-email/': typeof ApiCheckEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/dashboard/about': typeof ProtectedDashboardAboutRoute
  '/dashboard/agents': typeof ProtectedDashboardAgentsRoute
  '/dashboard/better-auth': typeof ProtectedDashboardBetterAuthRoute
  '/dashboard/conversations': typeof ProtectedDashboardConversationsRoute
  '/dashboard/custom-rules': typeof ProtectedDashboardCustomRulesRoute
  '/dashboard/knowledge-base': typeof ProtectedDashboardKnowledgeBaseRoute
  '/dashboard/risk-center': typeof ProtectedDashboardRiskCenterRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/upload-recordings': typeof ProtectedDashboardUploadRecordingsRoute
  '/dashboard/users': typeof ProtectedDashboardUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/api/check-email': typeof ApiCheckEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/_protected/dashboard/about': typeof ProtectedDashboardAboutRoute
  '/_protected/dashboard/agents': typeof ProtectedDashboardAgentsRoute
  '/_protected/dashboard/better-auth': typeof ProtectedDashboardBetterAuthRoute
  '/_protected/dashboard/conversations': typeof ProtectedDashboardConversationsRoute
  '/_protected/dashboard/custom-rules': typeof ProtectedDashboardCustomRulesRoute
  '/_protected/dashboard/knowledge-base': typeof ProtectedDashboardKnowledgeBaseRoute
  '/_protected/dashboard/risk-center': typeof ProtectedDashboardRiskCenterRoute
  '/_protected/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/_protected/dashboard/upload-recordings': typeof ProtectedDashboardUploadRecordingsRoute
  '/_protected/dashboard/users': typeof ProtectedDashboardUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/api/check-email/': typeof ApiCheckEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/onboarding'
    | '/dashboard/about'
    | '/dashboard/agents'
    | '/dashboard/better-auth'
    | '/dashboard/conversations'
    | '/dashboard/custom-rules'
    | '/dashboard/knowledge-base'
    | '/dashboard/risk-center'
    | '/dashboard/settings'
    | '/dashboard/upload-recordings'
    | '/dashboard/users'
    | '/api/auth/$'
    | '/dashboard/'
    | '/api/check-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/onboarding'
    | '/dashboard/about'
    | '/dashboard/agents'
    | '/dashboard/better-auth'
    | '/dashboard/conversations'
    | '/dashboard/custom-rules'
    | '/dashboard/knowledge-base'
    | '/dashboard/risk-center'
    | '/dashboard/settings'
    | '/dashboard/upload-recordings'
    | '/dashboard/users'
    | '/api/auth/$'
    | '/dashboard'
    | '/api/check-email'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/api/onboarding'
    | '/_protected/dashboard/about'
    | '/_protected/dashboard/agents'
    | '/_protected/dashboard/better-auth'
    | '/_protected/dashboard/conversations'
    | '/_protected/dashboard/custom-rules'
    | '/_protected/dashboard/knowledge-base'
    | '/_protected/dashboard/risk-center'
    | '/_protected/dashboard/settings'
    | '/_protected/dashboard/upload-recordings'
    | '/_protected/dashboard/users'
    | '/api/auth/$'
    | '/_protected/dashboard/'
    | '/api/check-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiOnboardingRoute: typeof ApiOnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckEmailIndexRoute: typeof ApiCheckEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding': {
      id: '/api/onboarding'
      path: '/api/onboarding'
      fullPath: '/api/onboarding'
      preLoaderRoute: typeof ApiOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-email/': {
      id: '/api/check-email/'
      path: '/api/check-email'
      fullPath: '/api/check-email/'
      preLoaderRoute: typeof ApiCheckEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/users': {
      id: '/_protected/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof ProtectedDashboardUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/upload-recordings': {
      id: '/_protected/dashboard/upload-recordings'
      path: '/dashboard/upload-recordings'
      fullPath: '/dashboard/upload-recordings'
      preLoaderRoute: typeof ProtectedDashboardUploadRecordingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/settings': {
      id: '/_protected/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof ProtectedDashboardSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/risk-center': {
      id: '/_protected/dashboard/risk-center'
      path: '/dashboard/risk-center'
      fullPath: '/dashboard/risk-center'
      preLoaderRoute: typeof ProtectedDashboardRiskCenterRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/knowledge-base': {
      id: '/_protected/dashboard/knowledge-base'
      path: '/dashboard/knowledge-base'
      fullPath: '/dashboard/knowledge-base'
      preLoaderRoute: typeof ProtectedDashboardKnowledgeBaseRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/custom-rules': {
      id: '/_protected/dashboard/custom-rules'
      path: '/dashboard/custom-rules'
      fullPath: '/dashboard/custom-rules'
      preLoaderRoute: typeof ProtectedDashboardCustomRulesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/conversations': {
      id: '/_protected/dashboard/conversations'
      path: '/dashboard/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof ProtectedDashboardConversationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/better-auth': {
      id: '/_protected/dashboard/better-auth'
      path: '/dashboard/better-auth'
      fullPath: '/dashboard/better-auth'
      preLoaderRoute: typeof ProtectedDashboardBetterAuthRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/agents': {
      id: '/_protected/dashboard/agents'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof ProtectedDashboardAgentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/about': {
      id: '/_protected/dashboard/about'
      path: '/dashboard/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof ProtectedDashboardAboutRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardAboutRoute: typeof ProtectedDashboardAboutRoute
  ProtectedDashboardAgentsRoute: typeof ProtectedDashboardAgentsRoute
  ProtectedDashboardBetterAuthRoute: typeof ProtectedDashboardBetterAuthRoute
  ProtectedDashboardConversationsRoute: typeof ProtectedDashboardConversationsRoute
  ProtectedDashboardCustomRulesRoute: typeof ProtectedDashboardCustomRulesRoute
  ProtectedDashboardKnowledgeBaseRoute: typeof ProtectedDashboardKnowledgeBaseRoute
  ProtectedDashboardRiskCenterRoute: typeof ProtectedDashboardRiskCenterRoute
  ProtectedDashboardSettingsRoute: typeof ProtectedDashboardSettingsRoute
  ProtectedDashboardUploadRecordingsRoute: typeof ProtectedDashboardUploadRecordingsRoute
  ProtectedDashboardUsersRoute: typeof ProtectedDashboardUsersRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardAboutRoute: ProtectedDashboardAboutRoute,
  ProtectedDashboardAgentsRoute: ProtectedDashboardAgentsRoute,
  ProtectedDashboardBetterAuthRoute: ProtectedDashboardBetterAuthRoute,
  ProtectedDashboardConversationsRoute: ProtectedDashboardConversationsRoute,
  ProtectedDashboardCustomRulesRoute: ProtectedDashboardCustomRulesRoute,
  ProtectedDashboardKnowledgeBaseRoute: ProtectedDashboardKnowledgeBaseRoute,
  ProtectedDashboardRiskCenterRoute: ProtectedDashboardRiskCenterRoute,
  ProtectedDashboardSettingsRoute: ProtectedDashboardSettingsRoute,
  ProtectedDashboardUploadRecordingsRoute:
    ProtectedDashboardUploadRecordingsRoute,
  ProtectedDashboardUsersRoute: ProtectedDashboardUsersRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiOnboardingRoute: ApiOnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckEmailIndexRoute: ApiCheckEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
