/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedUsersRouteImport } from './routes/_protected/users'
import { Route as ProtectedUploadRecordingsRouteImport } from './routes/_protected/upload-recordings'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedRiskCenterRouteImport } from './routes/_protected/risk-center'
import { Route as ProtectedKnowledgeBaseRouteImport } from './routes/_protected/knowledge-base'
import { Route as ProtectedCustomRulesRouteImport } from './routes/_protected/custom-rules'
import { Route as ProtectedConversationsRouteImport } from './routes/_protected/conversations'
import { Route as ProtectedBetterAuthRouteImport } from './routes/_protected/better-auth'
import { Route as ProtectedAgentsRouteImport } from './routes/_protected/agents'
import { Route as ProtectedAboutRouteImport } from './routes/_protected/about'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUploadRecordingsRoute =
  ProtectedUploadRecordingsRouteImport.update({
    id: '/upload-recordings',
    path: '/upload-recordings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRiskCenterRoute = ProtectedRiskCenterRouteImport.update({
  id: '/risk-center',
  path: '/risk-center',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKnowledgeBaseRoute = ProtectedKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomRulesRoute = ProtectedCustomRulesRouteImport.update({
  id: '/custom-rules',
  path: '/custom-rules',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConversationsRoute = ProtectedConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBetterAuthRoute = ProtectedBetterAuthRouteImport.update({
  id: '/better-auth',
  path: '/better-auth',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentsRoute = ProtectedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAboutRoute = ProtectedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/about': typeof ProtectedAboutRoute
  '/agents': typeof ProtectedAgentsRoute
  '/better-auth': typeof ProtectedBetterAuthRoute
  '/conversations': typeof ProtectedConversationsRoute
  '/custom-rules': typeof ProtectedCustomRulesRoute
  '/knowledge-base': typeof ProtectedKnowledgeBaseRoute
  '/risk-center': typeof ProtectedRiskCenterRoute
  '/settings': typeof ProtectedSettingsRoute
  '/upload-recordings': typeof ProtectedUploadRecordingsRoute
  '/users': typeof ProtectedUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/about': typeof ProtectedAboutRoute
  '/agents': typeof ProtectedAgentsRoute
  '/better-auth': typeof ProtectedBetterAuthRoute
  '/conversations': typeof ProtectedConversationsRoute
  '/custom-rules': typeof ProtectedCustomRulesRoute
  '/knowledge-base': typeof ProtectedKnowledgeBaseRoute
  '/risk-center': typeof ProtectedRiskCenterRoute
  '/settings': typeof ProtectedSettingsRoute
  '/upload-recordings': typeof ProtectedUploadRecordingsRoute
  '/users': typeof ProtectedUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_protected/about': typeof ProtectedAboutRoute
  '/_protected/agents': typeof ProtectedAgentsRoute
  '/_protected/better-auth': typeof ProtectedBetterAuthRoute
  '/_protected/conversations': typeof ProtectedConversationsRoute
  '/_protected/custom-rules': typeof ProtectedCustomRulesRoute
  '/_protected/knowledge-base': typeof ProtectedKnowledgeBaseRoute
  '/_protected/risk-center': typeof ProtectedRiskCenterRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/upload-recordings': typeof ProtectedUploadRecordingsRoute
  '/_protected/users': typeof ProtectedUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/about'
    | '/agents'
    | '/better-auth'
    | '/conversations'
    | '/custom-rules'
    | '/knowledge-base'
    | '/risk-center'
    | '/settings'
    | '/upload-recordings'
    | '/users'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/about'
    | '/agents'
    | '/better-auth'
    | '/conversations'
    | '/custom-rules'
    | '/knowledge-base'
    | '/risk-center'
    | '/settings'
    | '/upload-recordings'
    | '/users'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/signin'
    | '/signup'
    | '/_protected/about'
    | '/_protected/agents'
    | '/_protected/better-auth'
    | '/_protected/conversations'
    | '/_protected/custom-rules'
    | '/_protected/knowledge-base'
    | '/_protected/risk-center'
    | '/_protected/settings'
    | '/_protected/upload-recordings'
    | '/_protected/users'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/upload-recordings': {
      id: '/_protected/upload-recordings'
      path: '/upload-recordings'
      fullPath: '/upload-recordings'
      preLoaderRoute: typeof ProtectedUploadRecordingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/risk-center': {
      id: '/_protected/risk-center'
      path: '/risk-center'
      fullPath: '/risk-center'
      preLoaderRoute: typeof ProtectedRiskCenterRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knowledge-base': {
      id: '/_protected/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof ProtectedKnowledgeBaseRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/custom-rules': {
      id: '/_protected/custom-rules'
      path: '/custom-rules'
      fullPath: '/custom-rules'
      preLoaderRoute: typeof ProtectedCustomRulesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/conversations': {
      id: '/_protected/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ProtectedConversationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/better-auth': {
      id: '/_protected/better-auth'
      path: '/better-auth'
      fullPath: '/better-auth'
      preLoaderRoute: typeof ProtectedBetterAuthRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agents': {
      id: '/_protected/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ProtectedAgentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/about': {
      id: '/_protected/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ProtectedAboutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAboutRoute: typeof ProtectedAboutRoute
  ProtectedAgentsRoute: typeof ProtectedAgentsRoute
  ProtectedBetterAuthRoute: typeof ProtectedBetterAuthRoute
  ProtectedConversationsRoute: typeof ProtectedConversationsRoute
  ProtectedCustomRulesRoute: typeof ProtectedCustomRulesRoute
  ProtectedKnowledgeBaseRoute: typeof ProtectedKnowledgeBaseRoute
  ProtectedRiskCenterRoute: typeof ProtectedRiskCenterRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedUploadRecordingsRoute: typeof ProtectedUploadRecordingsRoute
  ProtectedUsersRoute: typeof ProtectedUsersRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAboutRoute: ProtectedAboutRoute,
  ProtectedAgentsRoute: ProtectedAgentsRoute,
  ProtectedBetterAuthRoute: ProtectedBetterAuthRoute,
  ProtectedConversationsRoute: ProtectedConversationsRoute,
  ProtectedCustomRulesRoute: ProtectedCustomRulesRoute,
  ProtectedKnowledgeBaseRoute: ProtectedKnowledgeBaseRoute,
  ProtectedRiskCenterRoute: ProtectedRiskCenterRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedUploadRecordingsRoute: ProtectedUploadRecordingsRoute,
  ProtectedUsersRoute: ProtectedUsersRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
